### ISSUE TITLE
Facing permission issue with NFS storageclass when creating application using postgres image

### ISSUE THREAD

**Issue by leo8a** [karmab/kcli-openshift4-baremetal#101]
When `statefulsets` (or any other object using persistent storage) use a `postgres` image, the pods fails to execute due to permission issues. This is caused by the current configs/perms on the available NFS-based `storageclass`: https://github.com/karmab/kcli-openshift4-baremetal/blob/master/scripts/10_nfs.sh

Manually, this is easy to solve by adding the `postgres` user to the NFS server and changing the `chown` and the `chmod` of the volume. More details on this resolution here: https://access.redhat.com/solutions/2817281

Automatically/Programmatically, the problem doesn't look trivial to solve.

/cc @karmab

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli-openshift4-baremetal/commit/68f5655540b60054e988f2b6fb0454d23354bc3b
