### ISSUE TITLE
README.md dead links

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli-openshift4-baremetal#60]
[parameters.yml.sample](https://github.com/karmab/kcli-openshift4-baremetal/blob/master/parameters.yml.sample) for a parameter file targetting baremetal nodes only
[parameters_virtual.yml.sample](https://github.com/karmab/kcli-openshift4-baremetal/blob/master/parameters_virtual.yml.sample) for one combining virtual masters and physical workers.

**Comment by karmab** [comment]
updated README
