### ISSUE TITLE
ztp official u/s container image moved

### ISSUE THREAD

**Issue by yuvalk** [karmab/kcli-openshift4-baremetal#65]
https://github.com/karmab/kcli-openshift4-baremetal/blob/50cc20fc79c3e642495c6d26b8df73632d575c82/ztp/scripts/siteconfig.sh#L11

no longer under emp1
it's in
quay.io/openshift-kni/ztp-site-generator:latest

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli-openshift4-baremetal/commit/4618852fedd93af1e1c07abeb7cd4d86b787d185 thanks!
