### ISSUE TITLE
[RFE] Optionally reset BMC when deploying

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli-openshift4-baremetal#77]
Sometimes the host installation fails because of the BMC and a reset should help fixing it.

This can be used:

```
ipmitool -I lanplus -U ${USER} -P ${PASSWORD} -H ${BMCIP} mc reset cold
```

or

```
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/Managers/bmc/Actions/Manager.Reset -d '{"ResetType": "GracefulRestart"}'
```

(via https://github.com/openbmc/docs/blob/master/REDFISH-cheatsheet.md#bmc-reboot)

**Comment by karmab** [comment]
please reopen when you re back!
